### ISSUE TITLE
Bug lhtranslation

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#154]
# Bug report
Environment :

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.2.4
URL | `https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html
~~~

#### Additional context

Last line of the error:
~~~ py
raise AttributeError('Provider not found')
~~~

The web is redirected:

Url | redirection
--- | ---
https://read.lhtranslation.com | https://lhtranslation.net
https://lhtranslation.com | https://lhtranslation.net

**Comment by 1271** [comment]
Thank. I'll fix it )

**Comment by 1271** [comment]
Please wait some more.
Now my life is quite intense, but I will soon return to normal :-)

**Comment by gromenauer** [comment]
Don't worry! Real life always takes precedence.

![](https://i.imgur.com/SdrB58c.gif)

**Comment by gromenauer** [comment]
Seems that adding in `manga_py/providers/__init__.py` the lines below, is not enough:
~~~ py
    'lhtranslation_com': [
        r'read\.lhtranslation\.com/manga-.',
        r'lhtranslation\.com/manga-.',
        r'lhtranslation\.net/manga-.',
        r'read\.lhtranslation\.com/truyen-.',
        r'lhtranslation\.com/truyen-.',
        r'lhtranslation\.net/truyen-.',
    ],
~~~
(Just tried)

**Comment by 1271** [comment]
This is enough, but it is possible that their url format has changed slightly
Tomorrow (on sat.) i will have time to deal with all the problems )

**Comment by 1271** [comment]
Please, check `manga-py 1.5.3`

**Comment by 1271** [comment]
Ohh.. Thx.
I will fixed it )

**Comment by 1271** [comment]
`Fails if url have truyen instead of manga`
Yes. This url did not pass by the condition. Corrected now.

`And fails to download from read.lhtranslation.com`
I have no problems downloading manga from the specified url
Perhaps there were problems with the server from the site

**Comment by gromenauer** [comment]
:bug: Still failing for me, in the secondary case (`read.lhtranslation.com` + `truyen`) :boom:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.3.1
URL | `https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html`


~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html
~~~

~~~ python
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/cli/__init__.py", line 45, in start
    self.parser.start()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 42, in start
    self.provider.process(self.params['url'], self.params)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 71, in process
    self._storage['manga_name'] = self.get_manga_name()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/gomanga_co.py", line 20, in get_manga_name
    return self._get_name(self._name_re)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 55, in _get_name
    return self.re.search(selector, url).group(1)
~~~

**Comment by 1271** [comment]
Hmm ...
On the working PC also does not work
Maybe I forgot to send something to github :confused:

**Comment by gromenauer** [comment]
Take a look at my comments at the https://github.com/yuru-yuri/manga-dl/commit/01f349c7cb548d568cf5b9ef82b779ed6e875b26 commit

**Comment by 1271** [comment]
Oh! That's my fault.
I forgot to fix the regular expression to get the folder name =)
Everything. Now it definitely works!

Thank you for your patience!

![sorry](https://user-images.githubusercontent.com/1452243/54544622-1a40bc80-49b1-11e9-93d1-526ec5d3dc3b.gif)

**Comment by gromenauer** [comment]
Happy to help :smile: !!

**Comment by gromenauer** [comment]
Still broken in non rewritten cases:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.3.2
URL | `https://lhtranslation.net/manga-isekai-demo-bunan-ni-ikitai-shoukougun.html` :+1:
URL | `https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html` :bug: :boom: 

In the second case it shows
~~~
Warning: 0 bit image downloaded, please check for redirection or broken content
Broken url: https://cdn.lhtranslation.net/Store/Manga/001_5c7b8318ecd4b.jpg
...
~~~

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `https://lhtranslation.net/manga-isekai-demo-bunan-ni-ikitai-shoukougun.html`
URL | `https://read.lhtranslation.com/truyen-isekai-demo-bunan-ni-ikitai-shoukougun.html`
